# Generated by Django 4.1.3 on 2022-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
